#!/usr/bin/env python3
"""
Agent D: Reporter
Generates comprehensive PDF reports and sends alerts
"""
import os
import json
from datetime import datetime
from typing import Dict

class ReporterAgent:
    """Generates reports and alerts for land opportunities"""
    
    def __init__(self, api_key: str = None):
        self.api_key = api_key or os.getenv('OPENAI_API_KEY')
    
    def generate_markdown_report(self, analysis: Dict, research: Dict) -> str:
        """
        Generate a markdown feasibility report
        
        Args:
            analysis: Analysis results
            research: Research data
            
        Returns:
            Markdown formatted report
        """
        parcel_id = analysis['parcel_id']
        eval_data = analysis['evaluation']
        costs = analysis['costs']
        roi = analysis['roi']
        
        report = f"""# Land Development Feasibility Report

**Parcel ID**: {parcel_id}
**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Match Score**: {eval_data['match_score']:.1f}%
**Recommendation**: {eval_data['recommendation']}

---

## Executive Summary

This parcel has been evaluated against your investment criteria and shows a **{eval_data['match_score']:.1f}% match**.

**Key Highlights:**
{chr(10).join(f'- {m}' for m in eval_data['matches'][:5])}

**Estimated ROI**: {roi['roi_percentage']:.1f}%
**Total Investment**: ${roi['total_investment']:,.0f}
**Estimated Profit**: ${roi['estimated_profit']:,.0f}

---

## Property Details

**Address**: {research['basic_info'].get('address', 'N/A')}
**Size**: {research['gis_data']['boundaries']['area_acres']} acres
**Current Zoning**: {research['zoning']['current_zoning']}
**Purchase Price**: ${research['basic_info'].get('price', 0):,.0f}

---

## Location & Infrastructure

**Topography**:
- Elevation: {research['gis_data']['topography']['elevation_min']}-{research['gis_data']['topography']['elevation_max']} ft
- Slope: {research['gis_data']['topography']['slope']}
- Flood Zone: {research['gis_data']['topography']['flood_zone']}

**Utilities**:
{chr(10).join(f'- {k.title()}: {v}' for k, v in research['gis_data']['infrastructure']['utilities'].items())}

**Access**:
- Road Type: {research['gis_data']['infrastructure']['road_access']}
- Distance to Highway: {research['gis_data']['infrastructure']['distance_to_highway']} miles

---

## Zoning & Regulations

**Current Zoning**: {research['zoning']['current_zoning']}

**Allowed Uses**:
{chr(10).join(f'- {use}' for use in research['zoning']['allowed_uses'])}

**Restrictions**:
- Minimum Lot Size: {research['zoning']['restrictions']['min_lot_size']:,} sq ft
- Maximum Height: {research['zoning']['restrictions']['max_height']} feet
- Maximum Coverage: {research['zoning']['restrictions']['max_coverage']*100}%

**Setbacks**:
- Front: {research['zoning']['restrictions']['setbacks']['front']} ft
- Side: {research['zoning']['restrictions']['setbacks']['side']} ft
- Rear: {research['zoning']['restrictions']['setbacks']['rear']} ft

---

## Environmental Assessment

**Wetlands**: {'Present' if research['environmental']['wetlands']['present'] else 'None detected'}

**Soil Quality**:
- Type: {research['environmental']['soil_quality']['type']}
- Drainage: {research['environmental']['soil_quality']['drainage']}
- Suitability: {research['environmental']['soil_quality']['suitability']}

**Hazard Assessment**:
- Flood Risk: {research['environmental']['hazards']['flood_risk']}
- Seismic Risk: {research['environmental']['hazards']['seismic_risk']}
- Wildfire Risk: {research['environmental']['hazards']['wildfire_risk']}

---

## Financial Analysis

### Development Costs

| Item | Cost |
|------|------|
| Land Preparation | ${costs['land_prep']:,.0f} |
| Utilities Connection | ${costs['utilities']:,.0f} |
| Roads & Access | ${costs['roads']:,.0f} |
| Permits & Fees | ${costs['permits']:,.0f} |
| Environmental Studies | ${costs['environmental']:,.0f} |
| Contingency (20%) | ${costs['contingency_20pct']:,.0f} |
| **Total Estimated** | **${costs['total_estimated']:,.0f}** |

### Return on Investment

| Metric | Value |
|--------|-------|
| Purchase Price | ${roi['purchase_price']:,.0f} |
| Development Costs | ${roi['development_costs']:,.0f} |
| Total Investment | ${roi['total_investment']:,.0f} |
| Estimated Value After Development | ${roi['estimated_value_after_dev']:,.0f} |
| Estimated Profit | ${roi['estimated_profit']:,.0f} |
| **ROI Percentage** | **{roi['roi_percentage']:.1f}%** |
| Estimated Timeline | {roi['payback_period_years']} years |

---

## Risks & Considerations

{chr(10).join(f'- {risk}' for risk in analysis['risks'])}

---

## Recommended Next Steps

{chr(10).join(f'{i+1}. {step}' for i, step in enumerate(analysis['next_steps']))}

---

## Disclaimer

This report is generated by AI and should be used for preliminary analysis only. All information should be verified with local authorities, professional surveyors, and legal counsel before making any investment decisions. Cost estimates are preliminary and subject to change.

---

*Report generated by Land Development AI Agent System*
"""
        return report
    
    def save_report(self, report: str, parcel_id: str, format: str = 'md') -> str:
        """
        Save report to file
        
        Args:
            report: Report content
            parcel_id: Parcel identifier
            format: File format (md, txt, html)
            
        Returns:
            Filename
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"report_{parcel_id}_{timestamp}.{format}"
        
        with open(filename, 'w') as f:
            f.write(report)
        
        print(f"💾 Report saved: {filename}")
        return filename
    
    def send_alert(self, analysis: Dict, recipient: str) -> bool:
        """
        Send alert about high-value opportunity
        
        Args:
            analysis: Analysis results
            recipient: Email or phone number
            
        Returns:
            Success status
        """
        if analysis['evaluation']['match_score'] >= 80:
            print(f"🚨 HIGH-VALUE ALERT: {analysis['parcel_id']}")
            print(f"   Match Score: {analysis['evaluation']['match_score']:.1f}%")
            print(f"   ROI: {analysis['roi']['roi_percentage']:.1f}%")
            print(f"   Would send to: {recipient}")
            # TODO: Implement actual email/SMS sending
            return True
        return False
    
    def generate_report(self, analysis: Dict, research: Dict, recipient: str = None) -> Dict:
        """
        Generate complete report and optionally send alert
        
        Args:
            analysis: Analysis results
            research: Research data
            recipient: Optional recipient for alerts
            
        Returns:
            Report metadata
        """
        print(f"\n📄 Generating report for {analysis['parcel_id']}")
        
        # Generate markdown report
        report = self.generate_markdown_report(analysis, research)
        
        # Save report
        filename = self.save_report(report, analysis['parcel_id'])
        
        # Send alert if high-value
        alert_sent = False
        if recipient:
            alert_sent = self.send_alert(analysis, recipient)
        
        result = {
            'parcel_id': analysis['parcel_id'],
            'report_file': filename,
            'alert_sent': alert_sent,
            'generated_at': datetime.now().isoformat()
        }
        
        print(f"✅ Report generation complete\n")
        return result

def main():
    """Example usage"""
    reporter = ReporterAgent()
    
    # Load analysis and research results
    with open('analysis_results.json', 'r') as f:
        analysis = json.load(f)
    
    with open('research_results.json', 'r') as f:
        research = json.load(f)
    
    # Generate report
    result = reporter.generate_report(
        analysis,
        research,
        recipient='developer@example.com'
    )
    
    print(f"📧 Report ready: {result['report_file']}")
    if result['alert_sent']:
        print(f"🚨 Alert sent to recipient")

if __name__ == '__main__':
    main()
